// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABSEMKwkWmaC8Ygx6vnzVBueiK4rzQiDs',
    appId: '1:1017186344866:web:a43e2c993ad602b1929cfb',
    messagingSenderId: '1017186344866',
    projectId: 'reddit-clone-37341',
    authDomain: 'reddit-clone-37341.firebaseapp.com',
    storageBucket: 'reddit-clone-37341.appspot.com',
    measurementId: 'G-P6SVZRDBTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCkpG4VWGS48EAa_Qeyz1IEiPcmofJiUA',
    appId: '1:1017186344866:android:705a7125f4817b43929cfb',
    messagingSenderId: '1017186344866',
    projectId: 'reddit-clone-37341',
    storageBucket: 'reddit-clone-37341.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8KUbZyKiiyamXhoE_7dZuzdHhBeEe54w',
    appId: '1:1017186344866:ios:f53c07783a010ac2929cfb',
    messagingSenderId: '1017186344866',
    projectId: 'reddit-clone-37341',
    storageBucket: 'reddit-clone-37341.appspot.com',
    iosClientId: '1017186344866-clnj6fq7ju12lttn2c73o929o1ooqep0.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
